steps:
  - name: "gcr.io/cloud-builders/docker"
    args: [ "build", "-t", "gcr.io/nutmeg-435109/concrete-crack-predictor", ".", "-f", "Dockerfile" ]

  - name: "gcr.io/cloud-builders/docker"
    args: [ "push", "gcr.io/nutmeg-435109/concrete-crack-predictor" ]